USE PottersSupplies;

GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_CustomerID FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_EmployeeID FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_StoreNumber FOREIGN KEY (StoreNumber) REFERENCES StoreLocations(StoreNumber)
ON UPDATE CASCADE
GO
ALTER TABLE Products WITH CHECK
ADD CONSTRAINT FK_SupplierID FOREIGN KEY (SupplierID) REFERENCES Suppliers(SupplierID)
ON UPDATE CASCADE
GO
ALTER TABLE Customers WITH CHECK
ADD CONSTRAINT FK_Zipcode FOREIGN KEY (Zipcode) REFERENCES ZipCode(Zipcode)
ON UPDATE CASCADE
GO
ALTER TABLE Suppliers WITH CHECK
ADD CONSTRAINT FK_SupplierZipcode FOREIGN KEY (SupplierZipcode) REFERENCES ZipCode(Zipcode)
ON DELETE NO ACTION
GO
ALTER TABLE Employees WITH CHECK
ADD CONSTRAINT FK_EmployeeStoreNumber FOREIGN KEY (EmployeeStoreNumber) REFERENCES StoreLocations(StoreNumber)
ON DELETE NO ACTION
GO
ALTER TABLE ItemsOrdered WITH CHECK
ADD CONSTRAINT FK_OrderNumber FOREIGN KEY (OrderNumber) REFERENCES Orders(OrderNumber)
ON UPDATE NO ACTION
GO
ALTER TABLE ItemsOrdered WITH CHECK
ADD CONSTRAINT FK_ProductNumber FOREIGN KEY (ProductNumber) REFERENCES Products(ProductNumber)
ON UPDATE NO ACTION
